/* Allegro datafile object indexes, produced by grabber v4.2.0, MSVC */
/* Datafile: f:\new\installer\grabber\disc.dat */
/* Date: Fri Jul 20 11:45:12 2012 */
/* Do not hand edit! */

#define BACK                             0        /* BMP  */
#define BACK_P                           1        /* PAL  */
#define CANCEL                           2        /* BMP  */
#define CHKBOX1                          3        /* BMP  */
#define CHKBOX2                          4        /* BMP  */
#define CHKBOX_P                         5        /* PAL  */
#define CLOSE                            6        /* BMP  */
#define FONTT                            7        /* BMP  */
#define FONTT_P                          8        /* PAL  */
#define S001                             9        /* BMP  */
#define S002                             10       /* BMP  */
#define S003                             11       /* BMP  */
#define S004                             12       /* BMP  */
#define S005                             13       /* BMP  */
#define S006                             14       /* BMP  */
#define S007                             15       /* BMP  */
#define S008                             16       /* BMP  */
#define S009                             17       /* BMP  */
#define S010                             18       /* BMP  */
#define S011                             19       /* BMP  */
#define S012                             20       /* BMP  */
#define S013                             21       /* BMP  */
#define S014                             22       /* BMP  */
#define S015                             23       /* BMP  */
#define S016                             24       /* BMP  */
#define S017                             25       /* BMP  */
#define S018                             26       /* BMP  */
#define S019                             27       /* BMP  */
#define S020                             28       /* BMP  */
#define S021                             29       /* BMP  */
#define S022                             30       /* BMP  */
#define S023                             31       /* BMP  */
#define S024                             32       /* BMP  */
#define S025                             33       /* BMP  */
#define S026                             34       /* BMP  */
#define S027                             35       /* BMP  */
#define S028                             36       /* BMP  */
#define S029                             37       /* BMP  */
#define S030                             38       /* BMP  */
#define T001                             39       /* BMP  */
#define T002                             40       /* BMP  */
#define T003                             41       /* BMP  */
#define T004                             42       /* BMP  */
#define T005                             43       /* BMP  */
#define T006                             44       /* BMP  */
#define T007                             45       /* BMP  */
#define T008                             46       /* BMP  */
#define T009                             47       /* BMP  */
#define T010                             48       /* BMP  */
#define T011                             49       /* BMP  */
#define T012                             50       /* BMP  */
#define T013                             51       /* BMP  */
#define TITLE                            52       /* BMP  */
#define TITLE_P                          53       /* PAL  */

